[package]
name = "vmod_reqwest"
version = "0.0.2"
edition = "2021"

[build-dependencies]
varnish = { git = "https://github.com/gquintard/varnish-rs", rev = "186f03c7ceb9b1faa18cc298fb1a1f4212a7f7b5" }
varnish-sys = { git = "https://github.com/gquintard/varnish-rs", rev = "186f03c7ceb9b1faa18cc298fb1a1f4212a7f7b5" }

[dependencies]
varnish = { git = "https://github.com/gquintard/varnish-rs", rev = "186f03c7ceb9b1faa18cc298fb1a1f4212a7f7b5" }
varnish-sys = { git = "https://github.com/gquintard/varnish-rs", rev = "186f03c7ceb9b1faa18cc298fb1a1f4212a7f7b5" }
regex = "1.5"
lru = "0.7.1"
bytes = "1.1.0"
reqwest = { version = "0.11", features = ["stream", "deflate", "gzip", "brotli", "native-tls"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
futures-util = "0.3"
hyper = "0.14.16"

[lib]
crate-type = ["cdylib"]
