[package]
name = "vmod_reqwest"
version = "0.0.2"
edition = "2021"

[build-dependencies]
varnish = { git = "https://github.com/gquintard/varnish-rs", rev = "f2206da4881fc9bc73f6abf6d33a572f035c0fe0" }
varnish-sys = { git = "https://github.com/gquintard/varnish-rs", rev = "f2206da4881fc9bc73f6abf6d33a572f035c0fe0" }

[dependencies]
varnish = { git = "https://github.com/gquintard/varnish-rs", rev = "f2206da4881fc9bc73f6abf6d33a572f035c0fe0" }
varnish-sys = { git = "https://github.com/gquintard/varnish-rs", rev = "f2206da4881fc9bc73f6abf6d33a572f035c0fe0" }
regex = "1.5"
lru = "0.7.1"
bytes = "1.1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }

[lib]
crate-type = ["cdylib"]
